### ISSUE TITLE
Incompatibility with psycopg 3.2

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#2480]
Upgrade to psycopg 3.2 is blocked due to 

```python
AttributeError: module 'psycopg_c.pq' has no attribute 'PGcancelConn'
Waiting for PostgreSQL to become available...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/venv/lib/python3.12/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 117, in <module>
    import_from_libpq()
  File "/venv/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 103, in import_from_libpq
    PGcancelConn = module.PGcancelConn
```

**Comment by sainak** [comment]
fixed in 5bb466b
