### ISSUE TITLE
Ambulance API doesn't work for add driver

### ISSUE THREAD

**Issue by abhiabhi94** [coronasafe/care#299]
While writing tests for the ambulance API, I noticed that the `POST` request doesn't accept the `pk` attribute.

API documentation: https://api.care.coronasafe.in/redoc/#operation/ambulance_add_driver

Current function handling the view: https://github.com/coronasafe/care/blob/master/care/facility/api/viewsets/ambulance.py#L44

Test function
```python
def test_ambulance_add_driver(self):
        """
        Test ambulance users can add drivers to the ambulance
            - verify response code is 201
            - verify the response data with posted data
            - verify the data from the database
        """
        ambulance = self.ambulance
        data = self.get_detail_representation(ambulance)
        driver_1 = {
            "name": "foo",
            "phone_number": "8888888888",
            "has_smart_phone": False,
        }
        driver_2 = {
            "name": "bar",
            "phone_number": "8888888888",
            "has_smart_phone": False,
        }
        data.update(drivers=[driver_1, driver_2])
        # remove created and modified date
        data.pop("created_date", None)
        data.pop("modified_date", None)

        response = self.client.post(
            self.get_url(ambulance.id, action="add_driver"), data, format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
``` 

Here data is
```json
{'id': 35, 'drivers': [], 'primary_district_object': {'id': 73, 'name': 'District1586559872.586183', 'state': 60}, 'secondary_district_object': None, 'third_district_object': None, 'created_date': <config.tests.helper.EverythingEquals object at 0x7f7641932d10>, 'modified_date': <config.tests.helper.EverythingEquals object at 0x7f7641932d10>, 'deleted': False, 'vehicle_number': 'KL12BL3456', 'owner_name': 'foo', 'owner_phone_number': '8888888888', 'owner_has_smart_phone': True, 'has_oxygen': False, 'has_ventilator': False, 'has_suction_machine': False, 'has_defibrillator': False, 'insurance_valid_till_year': 2020, 'ambulance_type': 1, 'price_per_km': None, 'has_free_service': False, 'primary_district': 73, 'secondary_district': None, 'third_district': None}
```
Error Traceback:
```python
ERROR: test_ambulance_add_driver (care.facility.tests.test_apis.test_ambulance_api.TestAmbulance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/curious/Dev/opensourceDev/care/care/facility/tests/test_apis/test_ambulance_api.py", line 255, in test_ambulance_add_driver
    self.get_url(ambulance.id, action="add_driver"), data, format="json",
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/test.py", line 294, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/test.py", line 207, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/test.py", line 232, in generic
    method, path, data, content_type, secure, **extra)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/django/test/client.py", line 481, in generic
    return self.request(**r)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/test.py", line 283, in request
    return super().request(**kwargs)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/test.py", line 235, in request
    request = super().request(**kwargs)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/django/test/client.py", line 563, in request
    raise exc_value
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/curious/.virtualenvs/corona-care/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: add_driver() got an unexpected keyword argument 'pk'
```

**Comment by abhiabhi94** [comment]
I have almost fixed the issue, but I have some questions: 
- Whether multiple drivers can be added in one request?
- What is the response returned? Currently, the response shown here https://api.care.coronasafe.in/redoc/#operation/ambulance_add_driver is not what is being returned from the function  https://github.com/coronasafe/care/blob/master/care/facility/api/viewsets/ambulance.py#L44

**Comment by vigneshhari** [comment]
Currently, we have a neat implementation of adding and removing drivers and editing them from the Django admin panel, since we are not letting anyone edit or remove the drivers other than the superuser this kind covers our needs at the moment.

**Comment by vigneshhari** [comment]
You can work up a solution for the same and implement it. no worries there.

**Comment by abhiabhi94** [comment]
> Currently, we have a neat implementation of adding and removing drivers and editing them from the Django admin panel, since we are not letting anyone edit or remove the drivers other than the superuser this kind covers our needs at the moment.

I think there's no point in writing the same code elsewhere. I was assuming the openAPI documentation as the source of truth. So, should I just add a check to ensure that the API is accessed by a superuser and through admin only, otherwise throw a permission error?

**Comment by tomahawk-pilot** [comment]
Decommissioned APi
