### ISSUE TITLE
Issue while running locally at migration 0293

### ISSUE THREAD

**Issue by Marmik2003** [coronasafe/care#780]
when we execute docker container, the error comes at migration 0293,
the following are error traces while migrating in docker:

```
+ echo 'running migrations'

+ python manage.py migrate

System check identified some issues:


WARNINGS:

users.User.asset: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.

HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

Traceback (most recent call last):

  File "manage.py", line 30, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute

running migrations

Operations to perform:

  Apply all migrations: account, admin, auth, authtoken, contenttypes, django_celery_beat, django_rest_passwordreset, facility, sessions, sites, socialaccount, users

Running migrations:

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped

    res = handle_func(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle

    post_migrate_state = executor.migrate(

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate

    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards

    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply

    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards

    self.code(from_state.apps, schema_editor)

  File "/app/care/facility/migrations/0293_auto_20220520_1941.py", line 9, in update_json_field_names

    with transaction.atomic:

AttributeError: __enter__

+ echo 'running migrations'

+ python manage.py migrate

  Applying facility.0293_auto_20220520_1941...running migrations

System check identified some issues:


WARNINGS:

users.User.asset: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.

HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

Operations to perform:

  Apply all migrations: account, admin, auth, authtoken, contenttypes, django_celery_beat, django_rest_passwordreset, facility, sessions, sites, socialaccount, users

Running migrations:

Traceback (most recent call last):

  File "manage.py", line 30, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped

    res = handle_func(*args, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle

    post_migrate_state = executor.migrate(

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate

    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards

    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 124, in apply

    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)

  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards

    self.code(from_state.apps, schema_editor)

  File "/app/care/facility/migrations/0293_auto_20220520_1941.py", line 9, in update_json_field_names

    with transaction.atomic:

AttributeError: __enter__
```

**Comment by Marmik2003** [comment]
fixed by #781
