### ISSUE TITLE
`python manage.py summarize` is not working

### ISSUE THREAD

**Issue by mathew-alex** [coronasafe/care#911]
Traceback (most recent call last):
  File "/app/manage.py", line 55, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/care/facility/management/commands/summarize.py", line 21, in handle
    PatientSummary()
  File "/app/care/facility/summarisation/patient_summary.py", line 77, in PatientSummary
    count = patients.filter(**filter).count()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1315, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1107, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: admitted_to

**Comment by Ashesh3** [comment]
Seems related to https://github.com/coronasafe/care/pull/841/

The line causing the error is to be removed since `admitted_to` is no longer needed.

https://github.com/coronasafe/care/pull/841/files#diff-1cfa8525a1bda136e828a93f18708d7aca15e41111ac3e0fbc9fc848a9a7a116L98

**Comment by skks1212** [comment]
@Ashesh3 please link this issue with your PR so it is closed on merge

**Comment by vigneshhari** [comment]
@mathew-alex close if the issue has been resolved.

**Comment by sainak** [comment]
resolved in https://github.com/coronasafe/care/pull/924
